# Generated by Django 6.0.1 on 2026-02-03 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_rel', to='api.user'),
        ),
        migrations.AlterField(
            model_name='items',
            name='task',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='items',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
